trigger:
  branches:
    include:
      - master
      - main
      - develop
      - feature/*

pool:
  name: CNAPP
  demands:
    - Agent.name -equals s1-agent

variables:
  GIT_DEPTH: '0'

stages:
  - stage: Cloning
    displayName: 'Clone Juice Shop Repo'
    jobs:
      - job: CloneRepo
        steps:
          - checkout: none
          - script: |
              git clone https://github.com/gameblezz/juice-shop.git
            displayName: 'Git Clone Juice Shop'

  - stage: Scan_Secrets_IAC_Vuln
    displayName: 'Scan Secrets, IaC and Vuln'
    dependsOn: Cloning
    jobs:
      - job: ScanJob
        steps:
          - script: |

              # targetBranch="${SYSTEM_PULLREQUEST_TARGETBRANCH:master}"

              # sourceBranch="${BUILD_SOURCEBRANCHNAME:minor}"
              
              echo "Source branch: $sourceBranch"
              echo "Target branch: $targetBranch"

              tag="TestCNAPP:Test"
              
              sudo /root/.local/bin/s1-cns-cli config \
                --service-user-api-token $(S1_SERVICE_USER_API_TOKEN) \
                --management-console-url https://apne1-1101-nfr.sentinelone.net \
                --scope-type SITE \
                --scope-id 2137821414163885691 \
                --tag "$tag"

              sudo /root/.local/bin/s1-cns-cli scan secret \
                -d ./ \
                --pull-request origin/minor origin/master \
                --publish-result \
                --repo-full-name gameblezz/juice-shop \
                --repo-url "https://github.com/gameblezz/juice-shop" \
                --provider GITHUB

              sudo /root/.local/bin/s1-cns-cli scan iac \
                -d ./ \
                --publish-result \
                --repo-full-name gameblezz/juice-shop \
                --repo-url "https://github.com/gameblezz/juice-shop.git" \
                --branch $sourceBranch \
                --provider GITHUB

              sudo /root/.local/bin/s1-cns-cli scan vuln -d ./
            env:
              S1_SERVICE_USER_API_TOKEN: $(S1_SERVICE_USER_API_TOKEN)
            displayName: 'Run SentinelOne Scans'

  - stage: Scan_Image
    displayName: 'Scan Docker Image'
    dependsOn: Scan_Secrets_IAC_Vuln
    jobs:
      - job: ImageScan
        steps:
          - script: |
              sudo /root/.local/bin/s1-cns-cli scan vuln \
                --docker-image bkimminich/juice-shop:latest \
                --generate-sbom \
                --sbom-format cyclonedx-json \
                --output-file /home/azuredevops/TESTSCAN.json
            displayName: 'Scan Docker Image with S1 CLI'

          - script: |
              sudo chown azuredevops:azuredevops /home/azuredevops/TESTSCAN.json
              echo "Check file exists:"
              ls -la /home/azuredevops/
            displayName: 'Verify SBOM Output'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '/home/azuredevops/TESTSCAN.json'
              artifactName: 'TESTSCAN'
            displayName: 'Publish SBOM Artifact'

  - stage: Download_Artifact
    displayName: 'Download Artifact'
    dependsOn: Scan_Image
    jobs:
      - job: DownloadJob
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'TESTSCAN'
              itemPattern: '*.json'
              targetPath: '/home/azuredevops/'
            displayName: 'Download SBOM Artifact'

          - script: |
              echo "Verify Downloaded Artifact:"
              ls -la /home/azuredevops/
            displayName: 'Check Downloaded File'

  - stage: Cleanup
    displayName: 'Cleanup Workspace'
    dependsOn: Download_Artifact
    condition: always()
    jobs:
      - job: CleanupJob
        steps:
          - script: |
              echo "Cleaning workspace..."
              sudo rm -rf juice-shop /home/azuredevops/TESTSCAN.json
            displayName: 'Clean workspace'
